lamartin/anciens/urls.py
from django.urls import path

from . import views

app_name="anciens"
urlpatterns = [
    path('', views.anciens, name='anciens'),
    path('<int:ancien_id>/', views.ancien, name='ancien'),
    path('<int:ancien_id>/edit', views.edit_ancien, name='edit'),
    path('create/', views.create, name="create"),
]

lamartin/lamartin/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('anciens.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

lamartin/anciens/models.py
from django.db import models
from django.forms import ModelForm
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from .validators import validate_letters, validate_alpha


# Create your models here.

class Ancien(models.Model):
    nom = models.CharField(max_length=20, validators=[validate_letters])
    prenom = models.CharField(max_length=20, validators=[validate_letters])
    ecole = models.CharField(max_length=20, validators=[validate_alpha])
    promo = models.IntegerField(default=0, validators=[MaxValueValidator(2023), MinValueValidator(2000)])
    specialite = models.CharField(max_length=40, validators=[validate_alpha])
    entreprise = models.CharField(max_length=30, validators=[validate_alpha], default="", blank=True)
    description = models.TextField(max_length=2000, validators=[validate_alpha])
    contact = models.CharField(max_length=25, default="", blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.nom} {self.prenom}, promo {self.promo}"


class AncienForm(ModelForm):
    class Meta:
        model = Ancien
        fields = ['nom', 'prenom', 'ecole', 'promo', 'specialite', 'entreprise', 'description', 'contact']

lamartin/anciens/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required

from .models import Ancien, AncienForm
# Create your views here.

@login_required
def anciens(request):
    anciens_list = Ancien.objects.order_by('promo')
    has_created = Ancien.objects.filter(user=request.user).exists()
    context = {
        "anciens_list" : anciens_list,
        "has_created" : has_created
    }
    return render(request, "anciens/index.html", context)

@login_required
def ancien(request, ancien_id):
    ancien = get_object_or_404(Ancien, pk=ancien_id)

    return render(request, "anciens/detail.html", {"ancien": ancien})

@login_required
def create(request):
    try:
        form = AncienForm(request.POST)
        if form.is_valid() and not Ancien.objects.filter(user=request.user).exists():
            new = form.save()
            new.user = request.user
            new.save()
            return redirect("/")
    except:
        return redirect("/")
    return redirect("/")

@login_required
def edit_ancien(request, ancien_id):
    entry = get_object_or_404(Ancien, pk=ancien_id)
    if request.method != "POST":
        form = AncienForm(instance=entry)
        return HttpResponse(form.as_p())
    else:
        form = AncienForm(instance=entry, data=request.POST)
        if form.is_valid() and (request.user == entry.user or request.user.is_superuser):
            form.save()
            return HttpResponseRedirect(f"/{ancien_id}")
        return HttpResponseRedirect(f"/{ancien_id}")

lamartin/anciens/templates/anciens/detail.html
{% extends 'base.html' %}
{% load range %}
{% block content %}
<a href="/"><i class="fa fa-arrow-left mb-5" aria-hidden="true"
    style="font-size: 1.5rem; color: black;"></i></a><br/>

<h1 class="display-4 fw-normal mb-5">

  {{ancien}}
  {% if ancien.user == user or user.is_superuser%}
  <button type="button" class="btn" id="edit-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <i class="bi bi-pencil-square" style="font-size:2em;"></i>
  </button>
  {% endif %}
</h1>
<h2>{{ancien.ecole}}, {{ancien.specialite}}</h2>
{% if ancien.entreprise %}
<h3>Travaille chez {{ancien.entreprise}}</h3>
{%endif%}
<p class="just lead fw-normal mb-5 mt-5">{{ancien.description}}</p>
<p>contact : {{ancien.contact}}</p>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="registerModalLabel">Modifier le profil</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{% url 'anciens:edit' ancien.id%}" method="post">
          {% csrf_token %}
          <fieldset>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <div class="mb-3">
              <label for="nomInput" class="form-label">Nom</label>
              <input value="{{ancien.nom}}" name="nom" type="text" class="form-control" id="nomInput"
                placeholder="Gaggioli" required>
            </div>
            <div class="mb-3">
              <label for="prenomInput" class="form-label">Prénom</label>
              <input value="{{ancien.prenom}}" name="prenom" type="text" class="form-control" id="prenomInput"
                placeholder="Viviane" required>
            </div>
            <div class="mb-3">
              <label for="promoInput" class="form-label">Promo</label>
              <select name="promo" type="text" class="form-control" id="promoInput">
                {% if ancien.promo == 2010 %}<option selected value="2010">2010</option>{% else %}<option value="2010">
                  2010</option>{% endif %}
                {% if ancien.promo == 2011 %}<option selected value="2011">2011</option>{% else %}<option value="2011">
                  2011</option>{% endif %}
                {% if ancien.promo == 2012 %}<option selected value="2012">2012</option>{% else %}<option value="2012">
                  2012</option>{% endif %}
                {% if ancien.promo == 2013 %}<option selected value="2013">2013</option>{% else %}<option value="2013">
                  2013</option>{% endif %}
                {% if ancien.promo == 2014 %}<option selected value="2014">2014</option>{% else %}<option value="2014">
                  2014</option>{% endif %}
                {% if ancien.promo == 2015 %}<option selected value="2015">2015</option>{% else %}<option value="2015">
                  2015</option>{% endif %}
                {% if ancien.promo == 2016 %}<option selected value="2016">2016</option>{% else %}<option value="2016">
                  2016</option>{% endif %}
                {% if ancien.promo == 2017 %}<option selected value="2017">2017</option>{% else %}<option value="2017">
                  2017</option>{% endif %}
                {% if ancien.promo == 2018 %}<option selected value="2018">2018</option>{% else %}<option value="2018">
                  2018</option>{% endif %}
                {% if ancien.promo == 2019 %}<option selected value="2019">2019</option>{% else %}<option value="2019">
                  2019</option>{% endif %}
                {% if ancien.promo == 2020 %}<option selected value="2020">2020</option>{% else %}<option value="2020">
                  2020</option>{% endif %}
              </select>
            </div>
            <div class="mb-3">
              <label for="ecoleInput" class="form-label">École</label>
              <input value="{{ancien.ecole}}" name="ecole" type="text" class="form-control" id="ecoleInput"
                placeholder="Céramique Limoges" required>
            </div>
            <div class="mb-3">
              <label for="specialiteInput" class="form-label">Spécialisation</label>
              <input value="{{ancien.specialite}}" name="specialite" type="text" class="form-control"
                id="specialiteInput" placeholder="Tasses en céramique" required>
            </div>
            <div class="mb-3">
              <label for="entrepriseInput" class="form-label">Entreprise</label>
              <input value="{{ancien.entreprise|default_if_none:''}}" name="entreprise" type="text" class="form-control"
                id="entrepriseInput" placeholder="Shadoks Inc.">
            </div>
            <div class="mb-3">
              <label for="commentaireInput" class="form-label">Commentaire</label>
              <textarea name="description" class="form-control" id="commentaireInput" placeholder="J'adore les chats"
                required>{{ancien.description}}</textarea>
            </div>
            <div class="mb-3">
              <label for="contactInput" class="form-label">Contact</label>
              <input value="{{ancien.contact|default_if_none:''}}" name="contact" type="text" class="form-control" id="contactInput"
                placeholder="viviane.gaggioli@jensaisrienquoi.com" required>
            </div>
            <div class="modal-footer d-block">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
              <button type="submit" class="btn btn-success float-end">Submit</button>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

lamartin/anciens/templates/anciens/index.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron mb-5">

  <h1 class="display-4">Salut PT!</h1>
  <p class="lead">Sur ce site sont référencés les anciens PT de la Martin. N'hésite pas à contacter un ancien pour
    parler de son école ou de son parcours !</p>
  <hr class="my-4">
  {% if not has_created and user.username != 'prof'%}
  
  <p>Tu peux t'inscrire en cliquant sur ce bouton</p>
  <p class="lead">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#registerModal">
      Inscription
    </button>

    <!-- Modal -->
    <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="registerModalLabel">Inscription</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form action="{% url 'anciens:create' %}" method="post">
              {% csrf_token %}
              <fieldset>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <div class="mb-3">
                  <label for="nomInput" class="form-label">Nom</label>
                  <input name="nom" type="text" class="form-control" id="nomInput" placeholder="Gaggioli" required>
                </div>
                <div class="mb-3">
                  <label for="prenomInput" class="form-label">Prénom</label>
                  <input name="prenom" type="text" class="form-control" id="prenomInput" placeholder="Viviane" required>
                </div>
                <div class="mb-3">
                  <label for="promoInput" class="form-label">Promo</label>
                  <select name="promo" type="text" class="form-control" id="promoInput">
                    <option value="2010">2010</option>
                    <option value="2011">2011</option>
                    <option value="2012">2012</option>
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label for="ecoleInput" class="form-label">École</label>
                  <input name="ecole" type="text" class="form-control" id="ecoleInput" placeholder="Céramique Limoges"
                    required>
                </div>
                <div class="mb-3">
                  <label for="specialiteInput" class="form-label">Spécialisation</label>
                  <input name="specialite" type="text" class="form-control" id="specialiteInput"
                    placeholder="Tasses en céramique" required>
                </div>
                <div class="mb-3">
                  <label for="entrepriseInput" class="form-label">Entreprise</label>
                  <input name="entreprise" type="text" class="form-control" id="entrepriseInput"
                    placeholder="Shadoks Inc.">
                </div>
                <div class="mb-3">
                  <label for="commentaireInput" class="form-label">Commentaire</label>
                  <textarea name="description" class="form-control" id="commentaireInput"
                    placeholder="J'adore les chats" required></textarea>
                </div>
                <div class="mb-3">
                  <label for="contactInput" class="form-label">Contact</label>
                  <input name="contact" type="text" class="form-control" id="contactInput"
                    placeholder="viviane.gaggioli@jensaisrienquoi.com" required>
                </div>
                <div class="modal-footer d-block">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                  <button type="submit" class="btn btn-success float-end">Submit</button>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </p>
  {% endif %}
</div>
<div class="row mx-1">
  <div class="col-12">
    {% if anciens_list %}
    <div class="table-responsive">
      <table class="table table-striped" id="anciens-table">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Promo</th>
            <th>École</th>
            <th>Spécialisation</th>
            <th>Entreprise</th>
            {% comment %} <th class="col-sm-5">Commentaire</th> {% endcomment %}
            {% comment %} <th>Contact</th> {% endcomment %}
            <th>Détails</th>
          </tr>
        </thead>
        <tbody>
          {% for ancien in anciens_list %}
          <tr>
            <td>{{ancien.nom}}</td>
            <td>{{ancien.prenom}}</td>
            <td>{{ancien.promo}}</td>
            <td>{{ancien.ecole}}</td>
            <td>{{ancien.specialite}}</td>
            <td>{{ancien.entreprise|default_if_none:""}}</td>
            {% comment %} <td class="text-center limit">{{ancien.description}}</td> {% endcomment %}
            {% comment %} <td>{{ancien.contact|default_if_none:""}}</td> {% endcomment %}
            <td><a href="{% url 'anciens:ancien' ancien.id%}"><i class="bi-three-dots"
                  style="font-size: 1.5rem; color: black;"></i></a></td>
          </tr>
          {%endfor%}

        </tbody>
      </table>

    </div>
    {%else%}
    <p>No data available.</p>
    {%endif%}


  </div>

</div>
{% endblock content %}

lamartin/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
    </script>
    <script src="https://use.fontawesome.com/0eb573a216.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% load static %}
    <script src="{% static 'anciens/limitText.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'anciens/style.css' %}">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
 
<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.js"></script>
    <title>PT Lamartin</title>
</head>

<body>
    <header class="p-3 bg-dark text-white mb-5">    
        <div class="navbar navbar-dark bg-dark box-shadow ">
            <div class="container d-flex justify-content-between">
                <h1><i class="bi bi-megaphone mx-5" style="font-size:1em;"></i><a href="/" class="header-link">Les plus beaux de la Martin</a></h1>
                {% if user.is_authenticated %}
                <a class="header-link" href="/accounts/logout"><i class="fa fa-sign-out" aria-hidden="true" style="font-size:3em;"></i></a>
                {% endif %}
            </div>
        </div>

    </header>
    <div class="container" id="content">
        {%block content%}{% endblock %}
    </div>
</body>

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2021 - contact : axelrousselot@outlook.fr</p>

    {% comment %} <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none"> {% endcomment %}
      {% comment %} <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg> {% endcomment %}
    {% comment %} </a> {% endcomment %}

    {% comment %} <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul> {% endcomment %}
  </footer>
</div>